# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "beijing" do |beijing|
    beijing.vm.box = "ubuntu/trusty64"
    beijing.vm.network "private_network", ip: "192.168.33.10"
  end
  config.vm.define "shanghai" do |shanghai|
    shanghai.vm.box = "ubuntu/trusty64"
    shanghai.vm.network "private_network", ip: "192.168.33.11"
  end
  config.vm.define "guangzhou" do |guangzhou|
    guangzhou.vm.box = "ubuntu/trusty64"
    guangzhou.vm.network "private_network", ip: "192.168.33.12"
  end
end
